/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Alert lifecycle message on cat/{site}/{machine}/alert and WS type 'alert' (plan §5.4). `alert` is the safety_alert record (HLD §6.11 + D10).
 */
export interface AlertV1 {
  schema: "alert.v1";
  ts: string;
  action: "RAISED" | "UPDATED" | "CLEARED" | "ACKED";
  alert: SafetyAlert;
}
export interface SafetyAlert {
  alert_id: string;
  ts: string;
  machine_id: string;
  operator_id: string | null;
  shift_id?: string | null;
  rule_id: string;
  level: "INFO" | "CAUTION" | "WARNING" | "CRITICAL";
  subject:
    | "SEATBELT"
    | "EXIT"
    | "TILT"
    | "PROXIMITY"
    | "GEOFENCE"
    | "POWERLINE"
    | "DTC"
    | "TEMP"
    | "FATIGUE"
    | "READINESS"
    | "HEAT"
    | "COUPLER"
    | "ANOMALY"
    | "EFFICIENCY"
    | "IDLE";
  /**
   * Exact inputs + thresholds that fired the rule (for /alerts/{id}/why).
   */
  state_snapshot: {};
  message_key: string;
  slots: {};
  channels: ("VISUAL" | "AUDIO" | "VIBRATION")[];
  acknowledged_at: string | null;
  ack_by: string | null;
  suppressed: boolean;
  suppress_reason: "COOLDOWN" | "HIGHER_ACTIVE" | null;
  escalated: boolean;
  active: boolean;
  cleared_at: string | null;
}
