/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Diagnostic trouble code change, sim -> ingest on cat/{site}/{machine}/dtc (HLD §8.1).
 */
export interface DtcV1 {
  schema: "dtc.v1";
  ts: string;
  site_id: string;
  machine_id: string;
  spn: number;
  fmi: number;
  /**
   * J1939 DM1 occurrence count.
   */
  oc?: number | null;
  /**
   * CAT event code, e.g. E361, when the machine reports one.
   */
  cat_code?: string | null;
  active: boolean;
  freeze_frame?: {} | null;
}
