/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Raw environment observation on cat/{site}/env (HLD §6.12). Derived fields (dew point, heat index, WBGT) are computed by ingest, not sent.
 */
export interface EnvV1 {
  schema: "env.v1";
  ts: string;
  site_id: string;
  source: "API" | "FORECAST_CACHE" | "MACHINE_SENSOR" | "MANUAL" | "SIM";
  temp_c?: number | null;
  rh_pct?: number | null;
  precip_mm_h?: number | null;
  rain_flag?: boolean | null;
  wind_kmh?: number | null;
  gust_kmh?: number | null;
  visibility_m?: number | null;
  ground_condition?: "DRY" | "WET" | "MUDDY" | null;
}
