/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Discrete machine event on cat/{site}/{machine}/event (HLD §6.9, §6.15).
 */
export interface EventV1 {
  schema: "event.v1";
  event_id: string;
  ts: string;
  machine_id: string;
  operator_id?: string | null;
  shift_id?: string | null;
  type:
    | "IGNITION_ON"
    | "IGNITION_OFF"
    | "SEATBELT_FASTENED"
    | "SEATBELT_UNFASTENED"
    | "SEAT_OCCUPIED"
    | "SEAT_VACATED"
    | "DOOR_OPEN"
    | "DOOR_CLOSED"
    | "HYD_LOCK"
    | "HYD_UNLOCK"
    | "PARK_BRAKE_ON"
    | "PARK_BRAKE_OFF"
    | "IDLE_START"
    | "IDLE_END"
    | "EXIT_ATTEMPT"
    | "EXIT_COMPLETED"
    | "MOUNT"
    | "COUPLER_UNLOCK"
    | "COUPLER_LOCK"
    | "COUPLER_TEST_PASSED"
    | "TILT_EXCEEDED"
    | "PROXIMITY_ENTER"
    | "PROXIMITY_EXIT"
    | "GEOFENCE_ENTER"
    | "GEOFENCE_EXIT"
    | "DTC_ACTIVE"
    | "DTC_CLEARED"
    | "DATA_STALE"
    | "DATA_RESTORED";
  severity: "INFO" | "CAUTION" | "WARNING" | "CRITICAL";
  rule_id?: string | null;
  /**
   * Monotonic per machine.
   */
  seq: number;
  source: "ingest" | "risk-engine" | "cv" | "operator";
  payload: {};
}
