/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Full hazard list, RETAINED on cat/{site}/hazards; also WS type 'hazards' (HLD §4.12, §6.11). Geometry in local site metres.
 */
export interface HazardsV1 {
  schema: "hazards.v1";
  site_id: string;
  as_of: string;
  pins: HazardPin[];
}
export interface HazardPin {
  pin_id: string;
  site_id: string;
  type: "WORKER_ZONE" | "OVERHEAD_LINE" | "SOFT_GROUND" | "BURIED_UTILITY" | "TRENCH" | "DROP_OFF" | "OTHER";
  geometry: LocalGeometry;
  /**
   * Point pins; default 10 m.
   */
  radius_m: number | null;
  /**
   * OVERHEAD_LINE only.
   */
  line_clearance_m: number | null;
  created_by: string;
  created_at: string;
  confirmations: number;
  expires_at: string | null;
  status: "ACTIVE" | "RESOLVED" | "PENDING_REVIEW";
  version: number;
  updated_at: string;
  deleted: boolean;
}
/**
 * GeoJSON-shaped Point or Polygon in local metres [x_m, y_m].
 */
export interface LocalGeometry {
  type: "Point" | "Polygon";
  coordinates: unknown[];
}
