/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Incident / near miss / hazard observation (HLD §6.11, §6.15). Syncs as P0.
 */
export interface IncidentV1 {
  schema: "incident.v1";
  incident_id: string;
  type: "NEAR_MISS" | "INCIDENT" | "INJURY" | "EQUIPMENT_DAMAGE" | "HAZARD_OBSERVATION";
  category: "PERSON_PROXIMITY" | "SLIP_FALL" | "ROLLOVER_RISK" | "POWER_LINE" | "UTILITY_STRIKE" | "OTHER";
  ts: string;
  x_m: number | null;
  y_m: number | null;
  machine_id: string | null;
  operator_id: string | null;
  reporter_id: string;
  severity_self: number;
  voice_note_path?: string | null;
  transcript?: string | null;
  /**
   * @maxItems 3
   */
  photo_paths: [] | [string] | [string, string] | [string, string, string];
  /**
   * Last 60 s telemetry summary.
   */
  state_snapshot?: {} | null;
  linked_alert_ids?: string[];
  hazard_pin_id?: string | null;
  status: "OPEN" | "REVIEWED" | "CLOSED";
  supervisor_notes?: string | null;
}
