/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Lesson catalogue + Replay templates, authored by P3 in data/lessons/lessons.json (HLD §6.12). Backend fills template placeholders only; never generates text.
 */
export interface LessonCatalogueV1 {
  schema: "lesson.v1";
  version: string;
  lessons: Lesson[];
  /**
   * Keyed by rule_id. Placeholders like {bucket_height_m} and {failed_checks} are filled from the exit's state snapshot.
   */
  replay_templates: {
    [k: string]: ReplayTemplate;
  };
}
export interface Lesson {
  lesson_id: string;
  title_key: string;
  format: "CARD" | "VIDEO" | "MCQ" | "REPLAY";
  duration_s: number;
  machine_family: "EXCAVATOR" | "WHEEL_LOADER" | "ANY";
  trigger_rule_ids: string[];
  tags?: string[];
  content_json?: {};
  media_path?: string | null;
  language: string;
  version: number;
  /**
   * Fallback lesson for a rule family when no specific lesson exists (HLD §4.11).
   */
  generic_for_subject?: string | null;
}
export interface ReplayTemplate {
  prompt: string;
  /**
   * @minItems 3
   * @maxItems 4
   */
  options: [string, string, string] | [string, string, string, string];
  correct_option: number;
  explanation: string;
  doc_reference?: string | null;
}
