/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Operator message on cat/{site}/{machine}/nudge and WS type 'nudge' (plan §5.4). Exit Guard ticks arrive via state.exit_checks.
 */
export interface NudgeV1 {
  schema: "nudge.v1";
  ts: string;
  nudge_id: string;
  alert_id: string;
  machine_id: string;
  rule_id: string;
  level: "INFO" | "CAUTION" | "WARNING" | "CRITICAL";
  display: "CHIP" | "BANNER" | "FULLSCREEN";
  /**
   * Key in contracts/i18n/en.json.
   */
  message_key: string;
  slots: {};
  /**
   * Id in contracts/audio_clips.yaml; null = no voice clip.
   */
  audio_clip: string | null;
  tone_pattern: "tone_info" | "tone_caution" | "tone_warning" | "tone_critical" | null;
  channels: ("VISUAL" | "AUDIO" | "VIBRATION")[];
  /**
   * Exit Guard only: checks to render, in order.
   */
  checklist?: ("ENGINE_RUNNING" | "HYD_UNLOCKED" | "IMPLEMENT_RAISED" | "MOVING" | "PARK_BRAKE_OFF" | "SLOPE")[];
}
