/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State Current */
        get: operations["state_current_state_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack
         * @description Ack ≠ clear: the alert stays active until its condition is definitively false.
         */
        post: operations["ack_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/why": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Why
         * @description The rule and the exact inputs + thresholds that fired it (HLD §10 "Why?").
         */
        get: operations["why_alerts__alert_id__why_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_sim_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_sim_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop
         * @description Replay mode: stop the running scenario, including its hold frames, so nothing but the
         *     real source (or a probe) publishes for the machine. P1's control API has no stop call
         *     (sim_control.md), so proxy mode answers 409.
         */
        post: operations["stop_sim_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Badge Id */
            badge_id: string;
            /** Pin */
            pin: string;
            /** Machine Id */
            machine_id?: string | null;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            /** Expires At */
            expires_at: string;
            operator: components["schemas"]["OperatorOut"];
            /** Shift */
            shift?: {
                [key: string]: unknown;
            } | null;
        };
        /** MachineStatus */
        MachineStatus: {
            /** State Class */
            state_class: string | null;
            /** Data Stale */
            data_stale: boolean | null;
            /** Sensor Health */
            sensor_health: {
                [key: string]: unknown;
            } | null;
            /** Disabled Rules */
            disabled_rules: {
                [key: string]: unknown;
            };
            /** Alerts Per Operating Hour */
            alerts_per_operating_hour: number | null;
            /** Dropped Frames */
            dropped_frames: number;
            /** Restarts */
            restarts: number;
            /** Last Restart S */
            last_restart_s: number | null;
        };
        /** OperatorOut */
        OperatorOut: {
            /** Operator Id */
            operator_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ScenarioList */
        ScenarioList: {
            /** Mode */
            mode: string;
            /** Scenarios */
            scenarios: string[];
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /** Name */
            name: string;
            /** Machine Id */
            machine_id?: string | null;
            /**
             * Speed
             * @description replay mode only: 10 = ten times faster
             * @default 1
             */
            speed: number;
        };
        /** ScenarioStarted */
        ScenarioStarted: {
            /** Ok */
            ok: boolean;
            /** Name */
            name: string;
            /** Started At */
            started_at?: string | null;
        };
        /** ScenarioStopped */
        ScenarioStopped: {
            /** Ok */
            ok: boolean;
            /** Stopped */
            stopped: string | null;
        };
        /** Snapshot */
        Snapshot: {
            /** As Of */
            as_of: string;
            /** State */
            state: {
                [key: string]: unknown;
            } | null;
            /** Alerts */
            alerts: {
                [key: string]: unknown;
            }[];
            /** Hazards */
            hazards: {
                [key: string]: unknown;
            };
            /** Sync */
            sync: {
                [key: string]: unknown;
            };
            /** Eta */
            eta: {
                [key: string]: unknown;
            } | null;
        };
        /** SystemStatus */
        SystemStatus: {
            /** As Of */
            as_of: string;
            /** Service */
            service: string;
            /** Site Id */
            site_id: string;
            /** Machines */
            machines: {
                [key: string]: components["schemas"]["MachineStatus"];
            };
            /** Mqtt */
            mqtt: {
                [key: string]: unknown;
            };
            /** Sync */
            sync: {
                [key: string]: unknown;
            };
            /** Models */
            models: {
                [key: string]: unknown;
            };
            /** Sim */
            sim: {
                [key: string]: unknown;
            };
            /** Auth Disabled */
            auth_disabled: boolean;
            /** Rules Version */
            rules_version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Why */
        Why: {
            /** Alert Id */
            alert_id: string;
            /** Rule Id */
            rule_id: string;
            /** Name */
            name: string;
            /** Level */
            level: string;
            /** Hld Ref */
            hld_ref: string;
            /** Message Key */
            message_key: string;
            /** Slots */
            slots: {
                [key: string]: unknown;
            };
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
            /** Active */
            active: boolean;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** As Of */
            as_of: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    system_status_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_current_state_current_get: {
        parameters: {
            query: {
                /** @description machine_id, e.g. EXC001 */
                machine: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    why_alerts__alert_id__why_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Why"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_sim_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioList"];
                };
            };
        };
    };
    start_sim_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_sim_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioStopped"];
                };
            };
        };
    };
}
