/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shift/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shift Start */
        post: operations["shift_start_shift_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shift/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shift End */
        post: operations["shift_end_shift_end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shift/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shift Current
         * @description The machine's shift now (ACTIVE, else today's row, else null) + the last handover note
         *     left on this machine by a previous shift.
         */
        get: operations["shift_current_shift_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_readiness_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Status */
        post: operations["set_status_tasks__task_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/eta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Eta */
        get: operations["task_eta_tasks__task_id__eta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/assigned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assigned */
        get: operations["assigned_lessons_assigned_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_lessons__assignment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{assignment_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete */
        post: operations["complete_lessons__assignment_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manager/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operators
         * @description Every operator with today's shift, task counts, 7-day alert count, pending lessons and
         *     the latest readiness rating (shown for context only, I10).
         */
        get: operations["operators_manager_operators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manager/operators/{operator_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operator Detail */
        get: operations["operator_detail_manager_operators__operator_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manager/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Options
         * @description Pick-lists for the assign form: machines, task types, soils, known zones.
         */
        get: operations["options_manager_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manager/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Day Tasks
         * @description Every machine's tasks for one site-local day (default today), plan vs actual.
         */
        get: operations["day_tasks_manager_tasks_get"];
        put?: never;
        /**
         * Assign
         * @description Create a task and assign it to an operator on a machine (outbox P1, I7).
         */
        post: operations["assign_manager_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manager/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reassign
         * @description Reassign (operator/machine) or reschedule a task that has not started.
         */
        patch: operations["reassign_manager_tasks__task_id__patch"];
        trace?: never;
    };
    "/state/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State Current */
        get: operations["state_current_state_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack
         * @description Ack ≠ clear: the alert stays active until its condition is definitively false.
         */
        post: operations["ack_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/why": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Why
         * @description The rule and the exact inputs + thresholds that fired it (HLD §10 "Why?").
         */
        get: operations["why_alerts__alert_id__why_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hazards */
        get: operations["list_hazards_hazards_get"];
        put?: never;
        /** Create Hazard */
        post: operations["create_hazard_hazards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazards/{pin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Hazard */
        delete: operations["delete_hazard_hazards__pin_id__delete"];
        options?: never;
        head?: never;
        /** Patch Hazard */
        patch: operations["patch_hazard_hazards__pin_id__patch"];
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Incident */
        post: operations["create_incident_incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/env/ground": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Env Ground
         * @description One-tap ground condition; WET makes `wet` true (R06 three-point prompt).
         */
        post: operations["env_ground_env_ground_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/env/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Env Manual
         * @description Manual temperature/RH when no sensor or feed is available (heat index, dew point).
         */
        post: operations["env_manual_env_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_sim_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_sim_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop
         * @description Replay mode: stop the running scenario, including its hold frames, so nothing but the
         *     real source (or a probe) publishes for the machine. P1's control API has no stop call
         *     (sim_control.md), so proxy mode answers 409.
         */
        post: operations["stop_sim_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics Active */
        get: operations["diagnostics_active_diagnostics_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Context Code */
            context_code?: string | null;
            /** Machine */
            machine?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Action Class */
            action_class: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /** As Of */
            as_of: string;
        };
        /** Body_create_incident_incidents_post */
        Body_create_incident_incidents_post: {
            /**
             * Incident
             * @description JSON: type, category, severity_self, …
             */
            incident: string;
            /** Voice */
            voice?: string | null;
            /**
             * Photos
             * @default []
             */
            photos: string[];
        };
        /** Citation */
        Citation: {
            /** N */
            n: number;
            /** Doc */
            doc: string;
            /** Section */
            section: string;
            /** Code Id */
            code_id: string | null;
        };
        /** CompleteIn */
        CompleteIn: {
            /** Score */
            score: number;
            /** Answers */
            answers?: unknown[];
        };
        /** DiagnosticCard */
        DiagnosticCard: {
            /** Code Id */
            code_id: string | null;
            /** Spn */
            spn: number | null;
            /** Fmi */
            fmi: number | null;
            /** Component */
            component: string | null;
            /** What Happened */
            what_happened: string | null;
            /** Why It Matters */
            why_it_matters: string | null;
            /** What To Do */
            what_to_do: string | null;
            /** Action Class */
            action_class: string;
            /** Source Doc */
            source_doc: string | null;
            /** Source Section */
            source_section: string | null;
        };
        /** Diagnostics */
        Diagnostics: {
            /** As Of */
            as_of: string;
            /** Machine Id */
            machine_id: string;
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticCard"][];
        };
        /** EndRequest */
        EndRequest: {
            /** Machine Id */
            machine_id?: string | null;
            /** Handover Note */
            handover_note?: string | null;
        };
        /**
         * Geometry
         * @description GeoJSON-shaped Point or Polygon in local site metres.
         */
        Geometry: {
            /**
             * Type
             * @enum {string}
             */
            type: "Point" | "Polygon";
            /** Coordinates */
            coordinates: unknown[];
        };
        /** Ground */
        Ground: {
            /**
             * Ground Condition
             * @enum {string}
             */
            ground_condition: "DRY" | "WET" | "MUDDY";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HazardIn */
        HazardIn: {
            /**
             * Type
             * @enum {string}
             */
            type: "WORKER_ZONE" | "OVERHEAD_LINE" | "SOFT_GROUND" | "BURIED_UTILITY" | "TRENCH" | "DROP_OFF" | "OTHER";
            geometry: components["schemas"]["Geometry"];
            /** Radius M */
            radius_m?: number | null;
            /** Line Clearance M */
            line_clearance_m?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Badge Id */
            badge_id: string;
            /** Pin */
            pin: string;
            /** Machine Id */
            machine_id?: string | null;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            /** Expires At */
            expires_at: string;
            operator: components["schemas"]["OperatorOut"];
            /** Shift */
            shift?: {
                [key: string]: unknown;
            } | null;
        };
        /** MachineStatus */
        MachineStatus: {
            /** State Class */
            state_class: string | null;
            /** Data Stale */
            data_stale: boolean | null;
            /** Sensor Health */
            sensor_health: {
                [key: string]: unknown;
            } | null;
            /** Disabled Rules */
            disabled_rules: {
                [key: string]: unknown;
            };
            /** Alerts Per Operating Hour */
            alerts_per_operating_hour: number | null;
            /** Dropped Frames */
            dropped_frames: number;
            /** Restarts */
            restarts: number;
            /** Last Restart S */
            last_restart_s: number | null;
        };
        /** Manual */
        Manual: {
            /** Temp C */
            temp_c: number;
            /** Rh Pct */
            rh_pct: number;
        };
        /** OperatorOut */
        OperatorOut: {
            /** Operator Id */
            operator_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** Patch */
        Patch: {
            /**
             * Action
             * @enum {string}
             */
            action: "CONFIRM" | "RESOLVE";
        };
        /** ReadinessIn */
        ReadinessIn: {
            /** Machine Id */
            machine_id?: string | null;
            /** Sleep Last 24H H */
            sleep_last_24h_h: number;
            /** Sleep Last 48H H */
            sleep_last_48h_h: number;
            /** Feel Score */
            feel_score: number;
            /** Rt Mean Ms */
            rt_mean_ms: number;
            /** Rt Sd Ms */
            rt_sd_ms?: number | null;
            /** Rt Lapses */
            rt_lapses: number;
            /**
             * Camera Used
             * @default false
             */
            camera_used: boolean;
            /** Long Blinks 20S */
            long_blinks_20s?: number | null;
        };
        /**
         * ReadinessOut
         * @description readiness.v1
         */
        ReadinessOut: {
            /**
             * Schema
             * @default readiness.v1
             */
            schema: string;
            /** Check Id */
            check_id: string;
            /** Operator Id */
            operator_id: string;
            /** Shift Id */
            shift_id: string | null;
            /** Ts */
            ts: string;
            /** Sleep Last 24H H */
            sleep_last_24h_h: number;
            /** Sleep Last 48H H */
            sleep_last_48h_h: number;
            /** Feel Score */
            feel_score: number;
            /** Rt Mean Ms */
            rt_mean_ms: number;
            /** Rt Sd Ms */
            rt_sd_ms: number | null;
            /** Rt Lapses */
            rt_lapses: number;
            /** Rt Delta Vs Baseline Pct */
            rt_delta_vs_baseline_pct: number | null;
            /** Baseline Source */
            baseline_source: string;
            /** Camera Used */
            camera_used: boolean;
            /** Long Blinks 20S */
            long_blinks_20s: number | null;
            /** Heat Level */
            heat_level: string;
            /** Score */
            score: number;
            /** Rating */
            rating: string;
            /** Reasons */
            reasons: string[];
            /** Supervisor Override */
            supervisor_override?: string | null;
        };
        /** ScenarioList */
        ScenarioList: {
            /** Mode */
            mode: string;
            /** Scenarios */
            scenarios: string[];
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /** Name */
            name: string;
            /** Machine Id */
            machine_id?: string | null;
            /**
             * Speed
             * @description replay mode only: 10 = ten times faster
             * @default 1
             */
            speed: number;
        };
        /** ScenarioStarted */
        ScenarioStarted: {
            /** Ok */
            ok: boolean;
            /** Name */
            name: string;
            /** Started At */
            started_at?: string | null;
        };
        /** ScenarioStopped */
        ScenarioStopped: {
            /** Ok */
            ok: boolean;
            /** Stopped */
            stopped: string | null;
        };
        /** ShiftOut */
        ShiftOut: {
            /** Shift */
            shift: {
                [key: string]: unknown;
            } | null;
            /** Previous Handover Note */
            previous_handover_note: string | null;
            /** As Of */
            as_of: string;
        };
        /** Snapshot */
        Snapshot: {
            /** As Of */
            as_of: string;
            /** State */
            state: {
                [key: string]: unknown;
            } | null;
            /** Alerts */
            alerts: {
                [key: string]: unknown;
            }[];
            /** Hazards */
            hazards: {
                [key: string]: unknown;
            };
            /** Sync */
            sync: {
                [key: string]: unknown;
            };
            /** Eta */
            eta: {
                [key: string]: unknown;
            } | null;
        };
        /** StartRequest */
        StartRequest: {
            /** Machine Id */
            machine_id?: string | null;
        };
        /** StatusIn */
        StatusIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "SCHEDULED" | "IN_PROGRESS" | "PAUSED" | "DONE" | "BACKLOG";
            /** Delay Reason */
            delay_reason?: ("WEATHER" | "WAITING_TRUCKS" | "BREAKDOWN" | "SAFETY_STOP" | "OTHER") | null;
            /** Actual Quantity */
            actual_quantity?: number | null;
        };
        /** SystemStatus */
        SystemStatus: {
            /** As Of */
            as_of: string;
            /** Service */
            service: string;
            /** Site Id */
            site_id: string;
            /** Machines */
            machines: {
                [key: string]: components["schemas"]["MachineStatus"];
            };
            /** Mqtt */
            mqtt: {
                [key: string]: unknown;
            };
            /** Sync */
            sync: {
                [key: string]: unknown;
            };
            /** Models */
            models: {
                [key: string]: unknown;
            };
            /** Model Detail */
            model_detail: {
                [key: string]: unknown;
            };
            /** Sim */
            sim: {
                [key: string]: unknown;
            };
            /** Auth Disabled */
            auth_disabled: boolean;
            /** Rules Version */
            rules_version: number;
        };
        /** TaskIn */
        TaskIn: {
            /** Operator Id */
            operator_id: string;
            /** Machine Id */
            machine_id: string;
            /** Task Type Id */
            task_type_id: string;
            /** Zone Id */
            zone_id?: string | null;
            /** Planned Quantity */
            planned_quantity: number;
            /** Soil Type */
            soil_type?: string | null;
            /**
             * Priority
             * @default 3
             */
            priority: number;
            /**
             * Scheduled Start
             * Format: date-time
             */
            scheduled_start: string;
            /**
             * Scheduled End
             * Format: date-time
             */
            scheduled_end: string;
        };
        /** TaskPatch */
        TaskPatch: {
            /** Operator Id */
            operator_id?: string | null;
            /** Machine Id */
            machine_id?: string | null;
            /** Zone Id */
            zone_id?: string | null;
            /** Planned Quantity */
            planned_quantity?: number | null;
            /** Priority */
            priority?: number | null;
            /** Scheduled Start */
            scheduled_start?: string | null;
            /** Scheduled End */
            scheduled_end?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Why */
        Why: {
            /** Alert Id */
            alert_id: string;
            /** Rule Id */
            rule_id: string;
            /** Name */
            name: string;
            /** Level */
            level: string;
            /** Hld Ref */
            hld_ref: string;
            /** Message Key */
            message_key: string;
            /** Slots */
            slots: {
                [key: string]: unknown;
            };
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
            /** Active */
            active: boolean;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** As Of */
            as_of: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    system_status_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shift_start_shift_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shift_end_shift_end_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shift_current_shift_current_get: {
        parameters: {
            query?: {
                /** @description default: the token's machine */
                machine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_readiness_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadinessIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_tasks_get: {
        parameters: {
            query?: {
                /** @description default: the machine's current shift */
                shift_id?: string | null;
                /** @description default: the token's machine */
                machine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_status_tasks__task_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_eta_tasks__task_id__eta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assigned_lessons_assigned_get: {
        parameters: {
            query?: {
                /** @description supervisor: another operator */
                operator_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_lessons__assignment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_lessons__assignment_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operators_manager_operators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    operator_detail_manager_operators__operator_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_manager_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    day_tasks_manager_tasks_get: {
        parameters: {
            query?: {
                /** @description site-local */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_manager_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_manager_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_current_state_current_get: {
        parameters: {
            query: {
                /** @description machine_id, e.g. EXC001 */
                machine: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    why_alerts__alert_id__why_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Why"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hazards_hazards_get: {
        parameters: {
            query?: {
                /** @description minx,miny,maxx,maxy in local metres */
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hazard_hazards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HazardIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_hazard_hazards__pin_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_hazard_hazards__pin_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pin_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_incident_incidents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_incident_incidents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    env_ground_env_ground_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ground"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    env_manual_env_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Manual"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_sim_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioList"];
                };
            };
        };
    };
    start_sim_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_sim_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioStopped"];
                };
            };
        };
    };
    diagnostics_active_diagnostics_active_get: {
        parameters: {
            query: {
                /** @description machine_id, e.g. EXC001 */
                machine: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_assistant_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
