/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Nearest person. cv -> engine on cat/{site}/{machine}/cv/proximity (5 Hz), sim fallback on .../sim/proximity. min_dist_m null + frame_ok true = no person; frame_ok false = UNKNOWN, never 'no person'.
 */
export interface ProximityV1 {
  schema: "proximity.v1";
  ts: string;
  machine_id: string;
  min_dist_m: number | null;
  sector?: "REAR" | "LEFT" | "RIGHT" | "FRONT" | null;
  conf?: number | null;
  frame_ok: boolean;
  source: "cv" | "sim";
}
