/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Machine frame, sim -> ingest on cat/{site}/{machine}/raw at 1 Hz + on switch change (plan §5.2). Any absent or null signal = UNKNOWN (I1). sim_label is eval-only (I9).
 */
export interface RawV1 {
  schema: "raw.v1";
  ts: string;
  site_id: string;
  machine_id: string;
  can?: RawCan;
  sens?: RawSens;
  sim_label?:
    | "UNSAFE_EXIT"
    | "BELT_BYPASS"
    | "LONG_IDLE_UNBELTED"
    | "HIGH_IDLE_RPM"
    | "FUEL_INEFFICIENCY"
    | "OVERHEAT_TREND"
    | "TILT_EXCURSION"
    | "PROXIMITY_INTRUSION"
    | "DTC"
    | null;
}
/**
 * J1939 values keyed by SPN.
 */
export interface RawCan {
  /**
   * parking_brake
   */
  "70"?: "ON" | "OFF" | null;
  /**
   * travel_speed_kmh (km/h)
   */
  "84"?: number | null;
  /**
   * engine_load_pct (%)
   */
  "92"?: number | null;
  /**
   * fuel_level_pct (%)
   */
  "96"?: number | null;
  /**
   * engine_oil_press_kpa (kPa)
   */
  "100"?: number | null;
  /**
   * coolant_temp_c (°C)
   */
  "110"?: number | null;
  /**
   * battery_v (V)
   */
  "168"?: number | null;
  /**
   * fuel_rate_lph (L/h)
   */
  "183"?: number | null;
  /**
   * engine_rpm (rpm)
   */
  "190"?: number | null;
  /**
   * engine_hours (h, monotonic)
   */
  "247"?: number | null;
  /**
   * fuel_used_total_l (L, monotonic)
   */
  "250"?: number | null;
  /**
   * transmission_gear (950 GC)
   */
  "523"?: number | null;
  /**
   * hyd_oil_temp_c (°C)
   */
  "1638"?: number | null;
  /**
   * def_level_pct (%)
   */
  "1761"?: number | null;
  /**
   * seatbelt
   */
  "1856"?: "FASTENED" | "UNFASTENED" | "FAULT" | null;
}
export interface RawSens {
  engine_state?: "OFF" | "CRANKING" | "RUNNING" | null;
  hyd_pump_press_kpa?: number | null;
  swing_rate_deg_s?: number | null;
  boom_angle_deg?: number | null;
  stick_angle_deg?: number | null;
  bucket_angle_deg?: number | null;
  /**
   * From Grade/implement system (D12).
   */
  bucket_height_m?: number | null;
  /**
   * From Grade/implement system (D12).
   */
  boom_tip_height_m?: number | null;
  payload_kg?: number | null;
  pass_count?: number | null;
  load_count?: number | null;
  idle_hours_total?: number | null;
  pitch_deg?: number | null;
  roll_deg?: number | null;
  /**
   * Local ENU metres.
   */
  x_m?: number | null;
  y_m?: number | null;
  heading_deg?: number | null;
  seat_occupied?: boolean | null;
  door_open?: boolean | null;
  hyd_lockout?: "LOCKED" | "UNLOCKED" | null;
  joystick_active?: boolean | null;
  lift_mode?: boolean | null;
  power_mode?: "ECO" | "POWER" | "SMART" | null;
  attachment_id?: string | null;
  coupler_lock?: "LOCKED" | "UNLOCKED" | "UNKNOWN" | null;
  cab_temp_c?: number | null;
  cab_ac_on?: boolean | null;
  /**
   * 950 GC only.
   */
  articulation_deg?: number | null;
  /**
   * Optional fine phase; display only.
   */
  activity_hint?:
    "OFF" | "IDLE" | "DIGGING" | "SWING_LOADED" | "DUMPING" | "SWING_EMPTY" | "TRAVELLING" | "LIFTING" | null;
}
