/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Shift-start readiness check result (HLD §6.12, §7.4). Advisory only, never blocks (I10).
 */
export interface ReadinessV1 {
  schema: "readiness.v1";
  check_id: string;
  operator_id: string;
  shift_id: string | null;
  ts: string;
  sleep_last_24h_h: number;
  sleep_last_48h_h: number;
  feel_score: number;
  rt_mean_ms: number;
  rt_sd_ms?: number | null;
  rt_lapses: number;
  rt_delta_vs_baseline_pct?: number | null;
  /**
   * POPULATION_DEFAULT = 'no personal baseline yet'.
   */
  baseline_source?: "PERSONAL" | "POPULATION_DEFAULT";
  camera_used: boolean;
  long_blinks_20s?: number | null;
  heat_level: "NONE" | "CAUTION" | "EXTREME_CAUTION" | "DANGER";
  score: number;
  rating: "GREEN" | "YELLOW" | "RED";
  reasons: string[];
  supervisor_override?: string | null;
}
