/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Operator State Engine output on cat/{site}/{machine}/state, on change <= 1 Hz (plan §5.3).
 */
export interface StateV1 {
  schema: "state.v1";
  ts: string;
  machine_id: string;
  operator_id: string | null;
  shift_id: string | null;
  class: "PRODUCTIVE" | "ATTENTION" | "UNSAFE" | "PARKED" | "OFF";
  active_rules: ActiveRule[];
  exit_state: "NONE" | "SAFE" | "SAFE_ENGINE_ON" | "UNSAFE";
  exit_checks: ExitChecks;
  readiness: "GREEN" | "YELLOW" | "RED" | null;
  sensor_health: SensorHealth;
  data_stale: boolean;
}
export interface ActiveRule {
  rule_id: string;
  level: "INFO" | "CAUTION" | "WARNING" | "CRITICAL";
}
/**
 * Live Exit Guard checklist (D1). PARK_BRAKE_OFF only for wheel loaders. Empty when no exit intent.
 */
export interface ExitChecks {
  ENGINE_RUNNING?: "PASS" | "FAIL" | "UNKNOWN";
  HYD_UNLOCKED?: "PASS" | "FAIL" | "UNKNOWN";
  IMPLEMENT_RAISED?: "PASS" | "FAIL" | "UNKNOWN";
  MOVING?: "PASS" | "FAIL" | "UNKNOWN";
  PARK_BRAKE_OFF?: "PASS" | "FAIL" | "UNKNOWN";
  SLOPE?: "PASS" | "FAIL" | "UNKNOWN";
}
export interface SensorHealth {
  seat: "OK" | "UNKNOWN" | "UNAVAILABLE";
  seatbelt: "OK" | "UNKNOWN" | "UNAVAILABLE";
  position: "OK" | "UNKNOWN" | "UNAVAILABLE";
  proximity: "OK" | "UNKNOWN" | "UNAVAILABLE";
  data: "OK" | "UNKNOWN" | "UNAVAILABLE";
}
