/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sync status on cat/{site}/{machine}/sync/status every 10 s + on change; WS type 'sync'.
 */
export interface SyncStatusV1 {
  schema: "sync_status.v1";
  ts: string;
  online: boolean;
  /**
   * Demo kill switch (D16); UI shows 'Forced offline (demo)'.
   */
  forced_offline: boolean;
  queue_depth: number;
  last_success_at: string | null;
}
