/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GET /sync/pull?stream=&cursor=&site_id= response.
 */
export interface SyncPullV1 {
  stream: "hazards" | "tasks" | "lessons" | "roster" | "models" | "forecast";
  items: PullItem[];
  next_cursor: number;
}
export interface PullItem {
  cursor: number;
  entity_id: string;
  op: "UPSERT" | "DELETE";
  payload: {};
}
