/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * POST /sync/push response. Lists every processed seq, duplicates included (idempotent).
 */
export interface SyncPushAckV1 {
  acked_seqs: number[];
}
