/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * POST /sync/push request body, gzip JSON (HLD §8.3, plan Phase 9). Batch <= 500.
 */
export interface SyncPushV1 {
  device_id: string;
  /**
   * @maxItems 500
   */
  batch: SyncItem[];
}
export interface SyncItem {
  seq: number;
  entity: string;
  entity_id: string;
  op: "UPSERT" | "DELETE";
  priority: number;
  payload: {};
}
