/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EtaPrediction = {
  p50_min: number;
  p90_min: number;
  eta: string;
  /**
   * @maxItems 3
   */
  drivers: [] | [EtaDriver] | [EtaDriver, EtaDriver] | [EtaDriver, EtaDriver, EtaDriver];
  /**
   * 'generic' for the fallback estimate.
   */
  model_version: string;
  /**
   * e.g. 'Estimate (generic)', 'Estimate (cohort)'.
   */
  label?: string | null;
  operator_rate_source?: "OPERATOR" | "COHORT" | "TASK_TYPE" | null;
} | null;

/**
 * Task with ETA prediction (HLD §6.7, §6.15).
 */
export interface TaskV1 {
  schema: "task.v1";
  task_id: string;
  shift_id: string;
  machine_id: string;
  operator_id: string;
  task_type_id: "TRUCK_LOAD" | "BULK_EXC" | "TRENCH" | "BACKFILL" | "GRADE" | "LOAD_CARRY" | "LIFT" | "CLEANUP";
  zone_id?: string | null;
  planned_quantity: number;
  unit: "M3" | "M" | "M2" | "LIFTS" | "HOURS";
  soil_type?: "LOAM" | "SAND_GRAVEL" | "CLAY_DRY" | "CLAY_WET" | "ROCK_BLASTED" | null;
  material_density_t_m3?: number | null;
  haul_distance_m?: number | null;
  trucks_assigned?: number | null;
  truck_capacity_t?: number | null;
  priority: number;
  depends_on?: string | null;
  scheduled_start: string;
  scheduled_end: string;
  status: "SCHEDULED" | "IN_PROGRESS" | "PAUSED" | "DONE" | "BACKLOG";
  actual_start?: string | null;
  actual_end?: string | null;
  actual_quantity?: number | null;
  delay_minutes?: number | null;
  delay_reason?: "WEATHER" | "WAITING_TRUCKS" | "BREAKDOWN" | "SAFETY_STOP" | "OTHER" | null;
  prediction?: EtaPrediction;
}
export interface EtaDriver {
  feature: string;
  effect_pct: number;
}
