/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Normalised 1 Hz telemetry, ingest -> all on cat/{site}/{machine}/telemetry (HLD §6.15). null = UNKNOWN. Groups marked optional below were added beyond the HLD sample (HLD §6.8 fields).
 */
export interface TelemetryV1 {
  schema: "telemetry.v1";
  ts: string;
  machine_id: string;
  operator_id: string | null;
  shift_id: string | null;
  engine: TelemetryEngine;
  hyd: TelemetryHyd;
  implement: TelemetryImplement;
  motion: TelemetryMotion;
  cab: TelemetryCab;
  pos: TelemetryPos;
  counters: TelemetryCounters;
  proximity: TelemetryProximity;
  /**
   * data_quality bitmask (stale/fault flags).
   */
  quality: number;
}
export interface TelemetryEngine {
  state: "OFF" | "CRANKING" | "RUNNING" | null;
  rpm: number | null;
  load_pct: number | null;
  fuel_rate_lph: number | null;
  fuel_used_total_l: number | null;
  fuel_level_pct: number | null;
  def_level_pct: number | null;
  hours: number | null;
  idle_hours_total: number | null;
  coolant_c: number | null;
  oil_press_kpa: number | null;
  battery_v?: number | null;
  power_mode?: "ECO" | "POWER" | "SMART" | null;
}
export interface TelemetryHyd {
  pump_press_kpa: number | null;
  oil_temp_c: number | null;
  lockout: "LOCKED" | "UNLOCKED" | null;
}
export interface TelemetryImplement {
  boom_deg: number | null;
  stick_deg: number | null;
  bucket_deg: number | null;
  bucket_height_m: number | null;
  boom_tip_height_m?: number | null;
  /**
   * bucket_height_m <= 0.3 (D12).
   */
  grounded: boolean | null;
  payload_kg: number | null;
  attachment_id: string | null;
  coupler: "LOCKED" | "UNLOCKED" | "UNKNOWN" | null;
}
export interface TelemetryMotion {
  /**
   * Coarse activity derived by backend (plan §5.2).
   */
  activity: "OFF" | "IDLE" | "WORKING" | "TRAVELLING" | "LIFTING" | null;
  /**
   * Fine phase from sim, display only.
   */
  activity_hint?:
    "OFF" | "IDLE" | "DIGGING" | "SWING_LOADED" | "DUMPING" | "SWING_EMPTY" | "TRAVELLING" | "LIFTING" | null;
  travel_kmh: number | null;
  swing_deg_s: number | null;
  pitch_deg: number | null;
  roll_deg: number | null;
  articulation_deg?: number | null;
  parking_brake?: "ON" | "OFF" | null;
  transmission_gear?: number | null;
}
export interface TelemetryCab {
  seatbelt: "FASTENED" | "UNFASTENED" | "FAULT" | null;
  seat_occupied: boolean | null;
  door_open: boolean | null;
  cab_temp_c: number | null;
  ac_on: boolean | null;
  joystick_active?: boolean | null;
  lift_mode?: boolean | null;
}
export interface TelemetryPos {
  x_m: number | null;
  y_m: number | null;
  heading_deg: number | null;
}
export interface TelemetryCounters {
  pass_count: number | null;
  load_count: number | null;
}
export interface TelemetryProximity {
  min_dist_m: number | null;
  sector: "REAR" | "LEFT" | "RIGHT" | "FRONT" | null;
}
