/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Every message on /ws/live and /ws/site (plan §5.4). `data` shape per type is documented in contracts/ws.md.
 */
export interface WsEnvelopeV1 {
  type:
    | "snapshot"
    | "state"
    | "telemetry"
    | "alert"
    | "nudge"
    | "event"
    | "hazards"
    | "sync"
    | "lesson"
    | "eta"
    | "health"
    | "ping";
  ts: string;
  data: {};
}
